<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'ditui_id' => 
  array (
    'field' => 'ditui_id',
    'label' => '递推ID',
    'pk' => true,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'city_id' => 
  array (
    'field' => 'city_id',
    'label' => '城市ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '城市ID',
    'default' => '',
    'SO' => false,
  ),
  'mobile' => 
  array (
    'field' => 'mobile',
    'label' => '手机号',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'mobile',
    'comment' => '',
    'default' => '',
    'SO' => '=',
  ),
  'passwd' => 
  array (
    'field' => 'passwd',
    'label' => '密码',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => false,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'money' => 
  array (
    'field' => 'money',
    'label' => '余额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'number',
    'comment' => '',
    'default' => '0.00',
    'SO' => false,
  ),
  'pmid' => 
  array (
    'field' => 'pmid',
    'label' => '推广码',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '推广码',
    'default' => '',
    'SO' => false,
  ),
  'reg_count' => 
  array (
    'field' => 'reg_count',
    'label' => '推荐注册用户数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '推荐注册用户数',
    'default' => '',
    'SO' => false,
  ),
  'total_money' =>
  array (
    'field' => 'total_money',
    'label' => '总收入',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'number',
    'comment' => '总收入',
    'default' => '0.00',
    'SO' => false,
  ),
  'order_count' => 
  array (
    'field' => 'order_count',
    'label' => '推荐后成功下单的会员数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '推荐后成功下单的会员数',
    'default' => '',
    'SO' => false,
  ),
  'name' => 
  array (
    'field' => 'name',
    'label' => '名称',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => 'like',
  ),
  'id_number' => 
  array (
    'field' => 'id_number',
    'label' => '身份证号',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '身份证号',
    'default' => '',
    'SO' => false,
  ),
  'id_photo' => 
  array (
    'field' => 'id_photo',
    'label' => '身份证图片',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'photo',
    'comment' => '身份证图片',
    'default' => '',
    'SO' => false,
  ),
  'account_type' => 
  array (
    'field' => 'account_type',
    'label' => '开户行',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '开户行',
    'default' => '',
    'SO' => false,
  ),
  'account_name' => 
  array (
    'field' => 'account_name',
    'label' => '帐户名称',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '帐户名称',
    'default' => '',
    'SO' => false,
  ),
  'account_number' => 
  array (
    'field' => 'account_number',
    'label' => '提现帐号',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '提现帐号',
    'default' => '',
    'SO' => false,
  ),
  'audit' => 
  array (
    'field' => 'audit',
    'label' => '是否审核',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'audit',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'clientip' => 
  array (
    'field' => 'clientip',
    'label' => '创建ip',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'clientip',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => '创建时间',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'dateline',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
);