<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'paotui_id' => 
  array (
    'field' => 'paotui_id',
    'label' => 'paotui_id',
    'pk' => true,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '跑腿订单ID',
    'default' => '',
    'SO' => false,
  ),
  'uid' => 
  array (
    'field' => 'uid',
    'label' => '用户UID',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '用户UID',
    'default' => '',
    'SO' => false,
  ),
  'addr' => 
  array (
    'field' => 'addr',
    'label' => '地址',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '收件人地址',
    'default' => '',
    'SO' => 'like',
  ),
  'house' => 
  array (
    'field' => 'house',
    'label' => '门号',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '收件人门号',
    'default' => '',
    'SO' => 'like',
  ),
  'contact' => 
  array (
    'field' => 'contact',
    'label' => '收件人',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '收件人',
    'default' => '',
    'SO' => false,
  ),
  'mobile' => 
  array (
    'field' => 'mobile',
    'label' => '收件电话',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '收件人电话',
    'default' => '',
    'SO' => false,
  ),
  'lat' => 
  array (
    'field' => 'lat',
    'label' => '收件纬度',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '收件人纬度坐标',
    'default' => '',
    'SO' => false,
  ),
  'lng' => 
  array (
    'field' => 'lng',
    'label' => '收件经度',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '收件人经度坐标',
    'default' => '',
    'SO' => false,
  ),
  'o_addr' => 
  array (
    'field' => 'o_addr',
    'label' => '取件址',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件/购买地址',
    'default' => '',
    'SO' => 'like',
  ),
  'o_house' => 
  array (
    'field' => 'o_house',
    'label' => '取件门号',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件/购买门号',
    'default' => '',
    'SO' => 'like',
  ),
  'o_contact' => 
  array (
    'field' => 'o_contact',
    'label' => '取件人',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件/购买联系人',
    'default' => '',
    'SO' => false,
  ),
  'o_mobile' => 
  array (
    'field' => 'o_mobile',
    'label' => '取件电话',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件/购买电话',
    'default' => '',
    'SO' => false,
  ),
  'o_lng' => 
  array (
    'field' => 'o_lng',
    'label' => '取件经度',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件/购买经度坐标',
    'default' => '',
    'SO' => false,
  ),
  'o_lat' => 
  array (
    'field' => 'o_lat',
    'label' => '取件纬度',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件/购买纬度坐标',
    'default' => '',
    'SO' => false,
  ),
  'intro' => 
  array (
    'field' => 'intro',
    'label' => '描述',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '描述',
    'default' => '',
    'SO' => false,
  ),
  'photo' => 
  array (
    'field' => 'photo',
    'label' => '图片',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '图片',
    'default' => '',
    'SO' => false,
  ),
  'voice' => 
  array (
    'field' => 'voice',
    'label' => '语音',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '语音',
    'default' => '',
    'SO' => false,
  ),
   'voice' => 
  array (
    'field' => 'voice',
    'label' => '语音',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '语音',
    'default' => '',
    'SO' => false,
  ),
  'voice_time' => 
  array (
    'field' => 'voice_time',
    'label' => '语音时间',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '语音时间',
    'default' => '0',
    'SO' => false,
  ),
  'danbao_amount' => 
  array (
    'field' => 'danbao_amount',
    'label' => '担保托管金额',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '担保托管金额',
    'default' => '0.00',
    'SO' => false,
  ),
  'jiesuan_amount' => 
  array (
    'field' => 'jiesuan_amount',
    'label' => '结算金额',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '结算金额',
    'default' => '0.00',
    'SO' => false,
  ),
  'type' => 
  array (
    'field' => 'type',
    'label' => '类型',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '类型',
    'default' => 'song',
    'SO' => false,
  ),
  'staff_id' => 
  array (
    'field' => 'staff_id',
    'label' => '配送员ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '配送员ID',
    'default' => '',
    'SO' => '=',
  ),
  'order_status' => 
  array (
    'field' => 'order_status',
    'label' => '订单状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '订单状态 0:未处理，1:已接单,',
    'default' => '',
    'SO' => '=',
  ),
  'pay_status' => 
  array (
    'field' => 'pay_status',
    'label' => '支付状态',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '支付状态 0:未支付，1:已支付',
    'default' => '',
    'SO' => '=',
  ),
  'pay_time' => 
  array (
    'field' => 'pay_time',
    'label' => '支付时间',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '支付时间UNIXTIME 当pay_status=1时有值',
    'default' => '',
    'SO' => false,
  ),
  'pay_code' => 
  array (
    'field' => 'pay_code',
    'label' => '支付类型',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '支付类型 wxpay:微信, alipay:支付宝, money:余额',
    'default' => '',
    'SO' => false,
  ),
  'pay_ip' => 
  array (
    'field' => 'pay_ip',
    'label' => '支付IP',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '支付IP',
    'default' => '',
    'SO' => false,
  ),
  'day' => 
  array (
    'field' => 'day',
    'label' => '日期Ymd',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '日期Ymd',
    'default' => '',
    'SO' => false,
  ),
  'clientip' => 
  array (
    'field' => 'clientip',
    'label' => '下单IP',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '下单IP',
    'default' => '',
    'SO' => false,
  ),
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => '下单时间',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '下单时间 UNIXTIME',
    'default' => '',
    'SO' => 'betweendate',
  ),
  'time' => 
  array (
    'field' => 'time',
    'label' => '收货时间',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '下单时间 UNIXTIME',
    'default' => '',
    'SO' => 'false',
  ),
  'o_time' => 
  array (
    'field' => 'o_time',
    'label' => '取件时间',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '下单时间 UNIXTIME',
    'default' => '',
    'SO' => 'false',
  ),
    
);