<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'shop_id' =>
  array (
    'field' => 'shop_id',
    'label' => '商家ID',
    'pk' => true,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'city_id' =>
  array (
    'field' => 'city_id',
    'label' => '城市ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => '=',
  ),
  'cate_id' =>
  array (
    'field' => 'cate_id',
    'label' => '分类ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '分类',
    'default' => '',
    'SO' => '=',
  ),
  'mobile' =>
  array (
    'field' => 'mobile',
    'label' => '手机号',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => false,
    'list' => true,
    'type' => 'mobile',
    'comment' => '手机号，登录用',
    'default' => '',
    'SO' => '=',
  ),
  'passwd' =>
  array (
    'field' => 'passwd',
    'label' => '密码',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'phone' =>
  array (
    'field' => 'phone',
    'label' => '联系电话',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => false,
    'list' => true,
    'type' => 'phone',
    'comment' => '联系电话',
    'default' => '',
    'SO' => false,
  ),
  'title' =>
  array (
    'field' => 'title',
    'label' => '商家名称',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => 'like',
  ),
  'money' =>
  array (
    'field' => 'money',
    'label' => '余额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'number',
    'comment' => '余额',
    'default' => '0.00',
    'SO' => false,
  ),
  'total_money' =>
  array (
      'field' => 'total_money',
      'label' => '总收入',
      'pk' => false,
      'add' => true,
      'edit' => true,
      'html' => false,
      'empty' => true,
      'show' => false,
      'list' => true,
      'type' => 'number',
      'comment' => '总收入',
      'default' => '0.00',
      'SO' => false,
    ), 
  'banner' =>
  array (
    'field' => 'banner',
    'label' => 'banner',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'photo',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'logo' =>
  array (
    'field' => 'logo',
    'label' => 'logo',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'photo',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'lat' =>
  array (
    'field' => 'lat',
    'label' => 'lat',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'lng' =>
  array (
    'field' => 'lng',
    'label' => 'lng',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'addr' =>
  array (
    'field' => 'addr',
    'label' => '地址',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => 'like',
  ),
  'views' =>
  array (
    'field' => 'views',
    'label' => '浏览',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'orders' =>
  array (
    'field' => 'orders',
    'label' => '订单总数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'comments' =>
  array (
    'field' => 'comments',
    'label' => '评论总数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'praise_num' =>
  array (
    'field' => 'praise_num',
    'label' => '好评数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => 'praise_num',
    'default' => '',
    'SO' => false,
  ),
  'score' =>
  array (
    'field' => 'score',
    'label' => '得分',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'number',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'score_fuwu' =>
  array (
    'field' => 'score_fuwu',
    'label' => '服务评分',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'number',
    'comment' => '服务评分',
    'default' => '',
    'SO' => false,
  ),
  'score_kouwei' =>
  array (
    'field' => 'score_kouwei',
    'label' => '口味评分',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'number',
    'comment' => '口味评分',
    'default' => '',
    'SO' => false,
  ),

  'first_amount' =>
  array (
    'field' => 'first_amount',
    'label' => '首单优惠',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'number',
    'comment' => '首单优惠',
    'default' => '0.00',
    'SO' => false,
  ),
  'min_amount' =>
  array (
    'field' => 'min_amount',
    'label' => '起送价',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'number',
    'comment' => '起送',
    'default' => '0.00',
    'SO' => false,
  ),
  'freight' =>
  array (
    'field' => 'freight',
    'label' => '配送费用',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => false,
    'type' => 'number',
    'comment' => '第三方配送费',
    'default' => '0.00',
    'SO' => false,
  ),
  'pei_amount' =>
  array (
    'field' => 'pei_amount',
    'label' => '运费',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'number',
    'comment' => '运费',
    'default' => '0.00',
    'SO' => false,
  ),
  'pei_time' =>
  array (
    'field' => 'pei_time',
    'label' => '配送时间',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '分钟，平均等待时间,从商家接单开始到订单结束',
    'default' => '',
    'SO' => false,
  ),
  'pei_distance' =>
  array (
    'field' => 'pei_distance',
    'label' => '配送距离',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '配送距离',
    'default' => '',
    'SO' => false,
  ),
  'pei_type' =>
  array (
    'field' => 'pei_type',
    'label' => '配送方式',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '0:自己送,1:第三方送，2:第三方代购及配送',
    'default' => '',
    'SO' => false,
  ),
  'yy_status' =>
  array (
    'field' => 'yy_status',
    'label' => '营业状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '0:打烊,1:营业中',
    'default' => '1',
    'SO' => false,
  ),
  'yy_stime' =>
  array (
    'field' => 'yy_stime',
    'label' => '开始营业时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '开始营业时间',
    'default' => '00:00:00',
    'SO' => false,
  ),
  'yy_ltime' =>
  array (
    'field' => 'yy_ltime',
    'label' => '打烊时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '打烊时间',
    'default' => '00:00:00',
    'SO' => false,
  ),
  'yy_xiuxi' =>
  array (
    'field' => 'yy_xiuxi',
    'label' => '中间休息时间',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '中间休息时间',
    'default' => '',
    'SO' => false,
  ),
  'is_new' =>
  array (
    'field' => 'is_new',
    'label' => '是否新店',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '是否新店',
    'default' => '0',
    'SO' => false,
  ),
  'online_pay' =>
  array (
    'field' => 'online_pay',
    'label' => '是否支持在线支付',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '0:不支持在线支付，1：支持在线支付',
    'default' => '',
    'SO' => false,
  ),
  'youhui' =>
  array (
    'field' => 'youhui',
    'label' => '优惠信息',
    'pk' => false,
    'add' => false,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '优惠信息',
    'default' => '',
    'SO' => false,
  ),
  'info' =>
  array (
    'field' => 'info',
    'label' => '简介',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'textarea',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'pmid' =>
  array (
    'field' => 'pmid',
    'label' => '推荐人',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => 'like',
  ),
  'audit' =>
  array (
    'field' => 'audit',
    'label' => '审核',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'verify_name' =>
  array (
    'field' => 'verify_name',
    'label' => '验证',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'closed' =>
  array (
    'field' => 'closed',
    'label' => '删除',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'clientip' =>
  array (
    'field' => 'clientip',
    'label' => '创建ip',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => false,
    'list' => true,
    'type' => 'clientip',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'dateline' =>
  array (
    'field' => 'dateline',
    'label' => '创建时间',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => false,
    'list' => true,
    'type' => 'dateline',
    'comment' => '',
    'default' => '',
    'SO' => 'betweendate',
  ),
  'tixian_percent' =>
  array (
    'field' => 'tixian_percent',
    'label' => '商户提现比例',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '商户提现比例',
    'default' => '',
    'SO' => false,
  ),
     'orderby' =>
  array (
    'field' => 'orderby',
    'label' => '排序',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'int',
    'comment' => '排序',
    'default' => '',
    'SO' => false,
  ),
);
